export const CATEGORIES_ACTION_TYPES = {
	FETCH_CATEGORIES_START: 'store/categories/FETCH_CATEGORIES_START',
	FETCH_CATEGORIES_SUCCESS: 'store/categories/FETCH_CATEGORIES_SUCCESS',
	FETCH_CATEGORIES_FAILED: 'store/categories/FETCH_CATEGORIES_FAILED',
};
